version: '3.8'

services:
  portfolio:
    # CAMBIO: Ya no usamos build, sino image
    # image: ghcr.io/usuario/nombre-repo:latest
    # ¡IMPORTANTE!: Todo en minúsculas
    image: ghcr.io/josecabezas/portfolio-flask:latest
    
    container_name: mi_portfolio_container
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env